/**
 * Promote Custom Variable to Dedicated Column
 * 
 * This script helps promote a custom variable from the JSONB column
 * to a dedicated database column for better query performance.
 * 
 * Usage:
 *   npx tsx scripts/promote-custom-variable-to-column.ts --variable "variable_name" --type text
 * 
 * Options:
 *   --variable  The name of the custom variable to promote (required)
 *   --type      The PostgreSQL data type (text, integer, boolean, text[]) (default: text)
 *   --dry-run   Preview changes without executing (default: false)
 * 
 * Example:
 *   npx tsx scripts/promote-custom-variable-to-column.ts --variable "seniority_level" --type text
 *   npx tsx scripts/promote-custom-variable-to-column.ts --variable "employee_count" --type integer
 */

import { createClient } from '@supabase/supabase-js'
import * as fs from 'fs'
import * as path from 'path'

// Parse command line arguments
const args = process.argv.slice(2)
const getArg = (name: string): string | undefined => {
  const index = args.indexOf(`--${name}`)
  return index !== -1 ? args[index + 1] : undefined
}
const hasFlag = (name: string): boolean => args.includes(`--${name}`)

const variableName = getArg('variable')
const dataType = getArg('type') || 'text'
const dryRun = hasFlag('dry-run')

if (!variableName) {
  console.error('❌ Error: --variable is required')
  console.log('\nUsage:')
  console.log('  npx tsx scripts/promote-custom-variable-to-column.ts --variable "variable_name" --type text')
  console.log('\nOptions:')
  console.log('  --variable  The name of the custom variable to promote (required)')
  console.log('  --type      PostgreSQL data type: text, integer, boolean, text[] (default: text)')
  console.log('  --dry-run   Preview changes without executing')
  process.exit(1)
}

// Validate data type
const validTypes = ['text', 'integer', 'boolean', 'text[]', 'jsonb', 'timestamptz']
if (!validTypes.includes(dataType)) {
  console.error(`❌ Error: Invalid data type "${dataType}"`)
  console.log(`Valid types: ${validTypes.join(', ')}`)
  process.exit(1)
}

// Connect to Supabase
const supabaseUrl = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseKey) {
  console.error('❌ Missing Supabase credentials!')
  console.error('Please set VITE_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY environment variables')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseKey)

// Helper to normalize variable name to column name
function toColumnName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
}

// Helper to generate timestamp for migration filename
function getMigrationTimestamp(): string {
  const now = new Date()
  const year = now.getFullYear()
  const month = String(now.getMonth() + 1).padStart(2, '0')
  const day = String(now.getDate()).padStart(2, '0')
  const hour = String(now.getHours()).padStart(2, '0')
  const minute = String(now.getMinutes()).padStart(2, '0')
  const second = String(now.getSeconds()).padStart(2, '0')
  return `${year}${month}${day}${hour}${minute}${second}`
}

async function analyzeVariable(): Promise<{ count: number; total: number; sampleValues: string[] }> {
  console.log(`\n📊 Analyzing variable: "${variableName}"`)
  
  // Get total count
  const { count: total } = await supabase
    .from('meetings_booked')
    .select('*', { count: 'exact', head: true })
  
  // Get records with this variable
  const { data, error } = await supabase
    .from('meetings_booked')
    .select('custom_variables_jsonb')
    .not('custom_variables_jsonb', 'is', null)
    .limit(1000)
  
  if (error) {
    console.error('Error fetching data:', error)
    return { count: 0, total: total || 0, sampleValues: [] }
  }
  
  let count = 0
  const sampleValues = new Set<string>()
  
  for (const row of data || []) {
    const customVars = row.custom_variables_jsonb as Record<string, any>
    if (customVars && customVars[variableName] !== undefined && customVars[variableName] !== null) {
      count++
      if (sampleValues.size < 5) {
        sampleValues.add(String(customVars[variableName]).substring(0, 50))
      }
    }
  }
  
  return { count, total: total || 0, sampleValues: Array.from(sampleValues) }
}

function generateMigration(columnName: string): string {
  const timestamp = getMigrationTimestamp()
  const migrationContent = `-- ============================================================================
-- MIGRATION: Add ${columnName} column to meetings_booked
-- ============================================================================
-- Auto-generated by promote-custom-variable-to-column.ts
-- Variable: "${variableName}"
-- Type: ${dataType}
-- ============================================================================

-- Step 1: Add the new column
ALTER TABLE meetings_booked 
  ADD COLUMN IF NOT EXISTS ${columnName} ${dataType.toUpperCase()};

-- Step 2: Backfill data from custom_variables_jsonb
UPDATE meetings_booked
SET ${columnName} = ${getBackfillExpression(columnName)}
WHERE custom_variables_jsonb->>'${variableName}' IS NOT NULL
  AND ${columnName} IS NULL;

-- Step 3: Add comment for documentation
COMMENT ON COLUMN meetings_booked.${columnName} IS 
  'Promoted from custom_variables_jsonb["${variableName}"]';

-- Step 4: Create index if column is frequently queried (optional)
-- CREATE INDEX IF NOT EXISTS idx_meetings_booked_${columnName} ON meetings_booked(${columnName});
`
  
  return migrationContent
}

function getBackfillExpression(columnName: string): string {
  switch (dataType) {
    case 'integer':
      return `(custom_variables_jsonb->>'${variableName}')::INTEGER`
    case 'boolean':
      return `CASE 
        WHEN LOWER(custom_variables_jsonb->>'${variableName}') IN ('true', 'yes', '1') THEN TRUE
        WHEN LOWER(custom_variables_jsonb->>'${variableName}') IN ('false', 'no', '0') THEN FALSE
        ELSE NULL
      END`
    case 'text[]':
      return `CASE 
        WHEN custom_variables_jsonb->'${variableName}' IS NOT NULL 
        THEN ARRAY(SELECT jsonb_array_elements_text(custom_variables_jsonb->'${variableName}'))
        ELSE NULL
      END`
    case 'jsonb':
      return `custom_variables_jsonb->'${variableName}'`
    case 'timestamptz':
      return `(custom_variables_jsonb->>'${variableName}')::TIMESTAMPTZ`
    default:
      return `custom_variables_jsonb->>'${variableName}'`
  }
}

function generateEdgeFunctionUpdate(columnName: string): string {
  return `
// Add to CUSTOM_VAR_TO_COLUMN_MAP in supabase/functions/sync-meetings-booked/index.ts:
'${variableName.toLowerCase()}': '${columnName}',
'${toColumnName(variableName)}': '${columnName}',
`
}

function generateTypeUpdate(columnName: string): string {
  const tsType = dataType === 'integer' ? 'number' 
    : dataType === 'boolean' ? 'boolean'
    : dataType === 'text[]' ? 'string[]'
    : 'string'
  
  return `
// Add to MeetingBooked interface in src/types/database.ts:
${columnName}?: ${tsType}
`
}

async function main() {
  console.log('🚀 Promote Custom Variable to Column')
  console.log('═'.repeat(50))
  console.log(`Variable: "${variableName}"`)
  console.log(`Data Type: ${dataType}`)
  console.log(`Dry Run: ${dryRun}`)
  
  const columnName = toColumnName(variableName)
  console.log(`Column Name: ${columnName}`)
  
  // Analyze the variable
  const stats = await analyzeVariable()
  const percentage = stats.total > 0 ? Math.round((stats.count / stats.total) * 100) : 0
  
  console.log(`\n📈 Statistics:`)
  console.log(`   Records with variable: ${stats.count.toLocaleString()} / ${stats.total.toLocaleString()} (${percentage}%)`)
  console.log(`   Sample values: ${stats.sampleValues.join(', ') || 'None found'}`)
  
  if (stats.count === 0) {
    console.log('\n⚠️  Warning: No records found with this variable. Are you sure the name is correct?')
  }
  
  // Generate migration
  const migration = generateMigration(columnName)
  const migrationFilename = `${getMigrationTimestamp()}_add_${columnName}_column.sql`
  const migrationPath = path.join(process.cwd(), 'supabase', 'migrations', migrationFilename)
  
  console.log(`\n📝 Generated Files:`)
  
  if (dryRun) {
    console.log(`\n--- Migration (${migrationFilename}) ---`)
    console.log(migration)
    console.log(`\n--- Edge Function Update ---`)
    console.log(generateEdgeFunctionUpdate(columnName))
    console.log(`\n--- TypeScript Type Update ---`)
    console.log(generateTypeUpdate(columnName))
  } else {
    // Write migration file
    fs.writeFileSync(migrationPath, migration)
    console.log(`   ✅ Migration: ${migrationPath}`)
    
    console.log(`\n🔧 Manual Steps Required:`)
    console.log(`   1. Add mapping to edge function:`)
    console.log(generateEdgeFunctionUpdate(columnName))
    console.log(`   2. Update TypeScript types:`)
    console.log(generateTypeUpdate(columnName))
    console.log(`   3. Deploy edge function: supabase functions deploy sync-meetings-booked`)
    console.log(`   4. Run migration: supabase db push`)
  }
  
  console.log(`\n✅ Done!`)
}

main().catch(console.error)




